"""预设事件模块
定义每个境界下玩家可选择的预设活动事件
"""

from .realms import get_realm_by_level, format_realm_info
from .config import PRESET_EVENT_GAIN_MIN, PRESET_EVENT_GAIN_MAX

# ==================== 各境界预设事件定义 ====================
# 每个事件包含：
#   - name: 事件名称
#   - description: 事件描述
#   - cultivation_range: 修为收益范围 (min, max)
#   - lifespan_cost: 基础寿命消耗
#   - npc_interact_chance: 触发NPC互动的概率
#   - npc_scene: NPC互动场景描述
#   - is_bad: 是否为坏事件（坏事件有较高收益波动但伴有惩罚风险）
#   - penalty_range: 坏事件惩罚范围 (min, max)，仅坏事件有
# events 按境界等级(1-8)索引

PRESET_EVENTS = {
    1: [  # 练气期（幼儿园）
        {
            "name": "大路跑步",
            "description": "在校园大路上跑步锻炼，呼吸新鲜空气，强身健体。",
            "cultivation_range": (5, 12),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.25,
            "npc_scene": "跑步相遇",
            "is_bad": False,
        },
        {
            "name": "学认数字",
            "description": "跟着老师学习认数字，从1数到100，增长智慧。",
            "cultivation_range": (8, 18),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "一起数数",
            "is_bad": False,
        },
        {
            "name": "听老师讲故事",
            "description": "围坐在一起听老师讲童话故事，培养想象力。",
            "cultivation_range": (6, 15),
            "lifespan_cost": 0,
            "npc_interact_chance": 0.2,
            "npc_scene": "听故事",
            "is_bad": False,
        },
        {
            "name": "画画涂鸦",
            "description": "拿起彩色笔在纸上自由涂鸦，发挥创造力。",
            "cultivation_range": (3, 10),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "一起画画",
            "is_bad": False,
        },
        {
            "name": "抢小朋友玩具",
            "description": "看到别人手里的玩具好玩，忍不住抢了过来。",
            "cultivation_range": (10, 20),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.5,
            "npc_scene": "争执抢夺",
            "is_bad": True,
            "penalty_range": (-15, -5),
        },
        {
            "name": "打架哭闹",
            "description": "因为一点小事就和小朋友打起来，满地打滚哭闹。",
            "cultivation_range": (10, 22),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.6,
            "npc_scene": "打架现场",
            "is_bad": True,
            "penalty_range": (-20, -8),
        },
        {
            "name": "奇遇骰子",
            "description": "路边捡到一个神秘骰子，掷出后竟引发天地异象！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "奇遇骰子",
        },
        {
            "name": "静心打坐",
            "description": "安静地坐在垫子上打坐冥想，感受体内的灵气流动。",
            "cultivation_range": (4, 10),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "一起打坐",
            "is_bad": False,
        },
    ],
    2: [  # 筑基期（小学）
        {
            "name": "语文课",
            "description": "上语文课，学习文言文、诗词鉴赏和写作技巧。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "语文课堂讨论",
            "is_bad": False,
            "subject": "语文",
        },
        {
            "name": "数学课",
            "description": "上数学课，学习函数、数列和立体几何。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.1,
            "npc_scene": "数学难题探讨",
            "is_bad": False,
            "subject": "数学",
        },
        {
            "name": "英语课",
            "description": "上英语课，学习语法、阅读和写作。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.1,
            "npc_scene": "英语对话练习",
            "is_bad": False,
            "subject": "英语",
        },
        {
            "name": "历史课",
            "description": "上历史课，学习中西方历史的重要事件。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "历史知识交流",
            "is_bad": False,
            "subject": "历史",
        },
        {
            "name": "地理课",
            "description": "上地理课，学习世界地理和气候知识。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "地理探索",
            "is_bad": False,
            "subject": "地理",
        },
        {
            "name": "抄同学作业被发现",
            "description": "早上来学校赶紧抄同学的作业，结果被老师抓了个正着。",
            "cultivation_range": (5, 25),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.5,
            "npc_scene": "一起挨批",
            "is_bad": True,
            "penalty_range": (-20, -10),
        },
        {
            "name": "上课捣乱被罚站",
            "description": "在课堂上讲小话、扔纸团，被老师罚站到走廊。",
            "cultivation_range": (8, 28),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.55,
            "npc_scene": "罚站难友",
            "is_bad": True,
            "penalty_range": (-25, -10),
        },
        {
            "name": "灵石猜猜看",
            "description": "路边遇到一个神秘庄家，邀你玩猜数字游戏，赢取灵石！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "灵石猜猜看",
        },
    ],
    3: [  # 结丹期（初中）
        {
            "name": "语文课",
            "description": "上语文课，学习文言文、诗词鉴赏和写作技巧。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "语文课堂讨论",
            "is_bad": False,
            "subject": "语文",
        },
        {
            "name": "数学课",
            "description": "上数学课，学习函数、数列和立体几何。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.1,
            "npc_scene": "数学难题探讨",
            "is_bad": False,
            "subject": "数学",
        },
        {
            "name": "英语课",
            "description": "上英语课，学习语法、阅读和写作。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.1,
            "npc_scene": "英语对话练习",
            "is_bad": False,
            "subject": "英语",
        },
        {
            "name": "历史课",
            "description": "上历史课，学习中西方历史的重要事件。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "历史知识交流",
            "is_bad": False,
            "subject": "历史",
        },
        {
            "name": "地理课",
            "description": "上地理课，学习世界地理和气候知识。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "地理探索",
            "is_bad": False,
            "subject": "地理",
        },
        {
            "name": "泡网吧打游戏",
            "description": "逃课去网吧打游戏，在虚拟世界里寻找刺激。",
            "cultivation_range": (15, 45),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.4,
            "npc_scene": "网吧偶遇",
            "is_bad": True,
            "penalty_range": (-30, -15),
        },
        {
            "name": "打架斗殴被处分",
            "description": "和同学发生口角后大打出手，被学校记过处分。",
            "cultivation_range": (20, 48),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.6,
            "npc_scene": "斗殴现场",
            "is_bad": True,
            "penalty_range": (-35, -20),
        },
        {
            "name": "灵兽捕捉",
            "description": "听说后山出现了一只灵兽，前去一探究竟！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "灵兽捕捉",
        },
    ],
    4: [  # 元婴期（高中）
        {
            "name": "模拟考试冲刺",
            "description": "全力备战模拟考试，刷题到深夜。",
            "cultivation_range": (30, 55),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.1,
            "npc_scene": "一起备考",
            "is_bad": False,
            "game": "exam",
        },
        {
            "name": "语文课",
            "description": "上语文课，学习文言文、诗词鉴赏和写作技巧。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "语文课堂讨论",
            "is_bad": False,
            "subject": "语文",
        },
        {
            "name": "数学课",
            "description": "上数学课，学习函数、数列和立体几何。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.1,
            "npc_scene": "数学难题探讨",
            "is_bad": False,
            "subject": "数学",
        },
        {
            "name": "地理课",
            "description": "上地理课，学习世界地理和气候知识。",
            "cultivation_range": (0, 0),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "地理探索",
            "is_bad": False,
            "subject": "地理",
        },
        {
            "name": "逃课去游戏厅",
            "description": "翻墙逃课去游戏厅打街机，心跳加速的刺激。",
            "cultivation_range": (20, 60),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.45,
            "npc_scene": "游戏厅相遇",
            "is_bad": True,
            "penalty_range": (-40, -20),
        },
        {
            "name": "顶撞老师请家长",
            "description": "在课堂上和老师顶嘴，态度恶劣被请家长。",
            "cultivation_range": (25, 55),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.5,
            "npc_scene": "办公室训话",
            "is_bad": True,
            "penalty_range": (-35, -15),
        },
        {
            "name": "炼丹小试",
            "description": "尝试炼制基础丹药，考验你的配药智慧！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "炼丹小试",
        },
        {
            "name": "灵兽捕捉",
            "description": "听说后山出现了一只灵兽，前去一探究竟！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "灵兽捕捉",
        },
    ],
    5: [  # 化神期（大学）
        {
            "name": "专业课学习",
            "description": "认真听专业课，钻研专业领域的深层知识。",
            "cultivation_range": (40, 75),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.15,
            "npc_scene": "课堂讨论",
            "is_bad": False,
        },
        {
            "name": "图书馆自习",
            "description": "在图书馆安静地自习，查阅资料，撰写论文。",
            "cultivation_range": (35, 65),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.1,
            "npc_scene": "图书馆相遇",
            "is_bad": False,
        },
        {
            "name": "实习实践",
            "description": "去企业实习，将所学知识应用到实际工作中。",
            "cultivation_range": (30, 70),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.3,
            "npc_scene": "实习同事",
            "is_bad": False,
        },
        {
            "name": "参加学术讲座",
            "description": "去听大牛教授的学术讲座，接触前沿知识。",
            "cultivation_range": (25, 55),
            "lifespan_cost": 1,
            "npc_interact_chance": 0.25,
            "npc_scene": "讲座听众",
            "is_bad": False,
        },
        {
            "name": "通宵打游戏挂科",
            "description": "通宵和室友开黑打游戏，第二天考试直接睡过头挂科。",
            "cultivation_range": (25, 75),
            "lifespan_cost": 4,
            "npc_interact_chance": 0.4,
            "npc_scene": "开黑室友",
            "is_bad": True,
            "penalty_range": (-50, -25),
        },
        {
            "name": "翘课被记过",
            "description": "经常翘课被辅导员发现，累计旷课被全校通报记过。",
            "cultivation_range": (30, 70),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.45,
            "npc_scene": "辅导员谈话",
            "is_bad": True,
            "penalty_range": (-45, -20),
        },
        {
            "name": "炼丹小试",
            "description": "尝试炼制基础丹药，考验你的配药智慧！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "炼丹小试",
        },
        {
            "name": "秘境碎石",
            "description": "发现一处灵石秘境，挥锤开采吧！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "秘境碎石",
        },
    ],
    6: [  # 炼虚期（硕士）
        {
            "name": "文献阅读与研究",
            "description": "文献阅读与研究活动",
            "cultivation_range": (0, 10),
            "npc_interact_chance": 0.2,
            "npc_scene": "通用场景",
            "is_bad": False,
        },
        {
            "name": "做实验/写代码",
            "description": "在实验室做实验验证想法，或者写代码跑数据。",
            "cultivation_range": (45, 110),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.2,
            "npc_scene": "实验室伙伴",
            "is_bad": False,
        },
        {
            "name": "参加学术会议",
            "description": "去参加国内学术会议，做海报展示或口头报告。",
            "cultivation_range": (40, 95),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.35,
            "npc_scene": "会议交流",
            "is_bad": False,
        },
        {
            "name": "数据造假被撤稿",
            "description": "为赶进度伪造实验数据，被审稿人发现后撤稿加通报批评。",
            "cultivation_range": (40, 120),
            "lifespan_cost": 5,
            "npc_interact_chance": 0.5,
            "npc_scene": "学术委员会",
            "is_bad": True,
            "penalty_range": (-60, -30),
        },
        {
            "name": "摸鱼摆烂被导师约谈",
            "description": "整天摸鱼不干活，进度拖垮被导师叫去办公室严肃约谈。",
            "cultivation_range": (35, 90),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.55,
            "npc_scene": "导师谈话",
            "is_bad": True,
            "penalty_range": (-50, -25),
        },
        {
            "name": "秘境碎石",
            "description": "发现一处灵石秘境，挥锤开采吧！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "秘境碎石",
        },
        {
            "name": "奇遇骰子",
            "description": "路边捡到一个神秘骰子，掷出后竟引发天地异象！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "奇遇骰子",
        },
        {
            "name": "撰写小论文",
            "description": "认真撰写课程小论文，查阅文献反复修改打磨。",
            "cultivation_range": (35, 75),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.1,
            "npc_scene": "论文交流",
            "is_bad": False,
        },
    ],
    7: [  # 合体期（博士）
        {
            "name": "前沿课题研究",
            "description": "深入研究领域内的前沿难题，力求突破性进展。",
            "cultivation_range": (70, 180),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.1,
            "npc_scene": "学术探讨",
            "is_bad": False,
        },
        {
            "name": "发顶刊/顶会",
            "description": "将研究成果投稿到顶级期刊或会议，经历严苛审稿。",
            "cultivation_range": (80, 200),
            "lifespan_cost": 4,
            "npc_interact_chance": 0.15,
            "npc_scene": "审稿交流",
            "is_bad": False,
        },
        {
            "name": "审稿/当编委",
            "description": "担任期刊审稿人或编委，评审同行的工作。",
            "cultivation_range": (50, 130),
            "lifespan_cost": 2,
            "npc_interact_chance": 0.2,
            "npc_scene": "审稿讨论",
            "is_bad": False,
        },
        {
            "name": "开题/答辩",
            "description": "准备博士开题报告或毕业论文答辩，接受专家质询。",
            "cultivation_range": (60, 160),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.25,
            "npc_scene": "答辩现场",
            "is_bad": False,
        },
        {
            "name": "学术不端被调查",
            "description": "被举报学术不端，学校成立调查组进行严肃调查。",
            "cultivation_range": (50, 150),
            "lifespan_cost": 5,
            "npc_interact_chance": 0.6,
            "npc_scene": "调查组约谈",
            "is_bad": True,
            "penalty_range": (-80, -40),
        },
        {
            "name": "怼导师被延毕",
            "description": "和导师大吵一架后关系破裂，导师暗示延毕处理。",
            "cultivation_range": (55, 140),
            "lifespan_cost": 4,
            "npc_interact_chance": 0.55,
            "npc_scene": "争吵冲突",
            "is_bad": True,
            "penalty_range": (-70, -35),
        },
        {
            "name": "秘境碎石",
            "description": "发现一处灵石秘境，挥锤开采吧！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "秘境碎石",
        },
        {
            "name": "奇遇骰子",
            "description": "路边捡到一个神秘骰子，掷出后竟引发天地异象！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "奇遇骰子",
        },
    ],
    8: [  # 大乘期（博士后）
        {
            "name": "申请科研基金",
            "description": "申请科研基金活动",
            "cultivation_range": (0, 10),
            "npc_interact_chance": 0.2,
            "npc_scene": "通用场景",
            "is_bad": False,
        },
        {
            "name": "国际合作项目",
            "description": "与国外顶尖团队开展国际合作研究，交流学术思想。",
            "cultivation_range": (100, 250),
            "lifespan_cost": 4,
            "npc_interact_chance": 0.3,
            "npc_scene": "国际合作者",
            "is_bad": False,
        },
        {
            "name": "带课题组",
            "description": "带领课题组青年学者和学生开展科研工作。",
            "cultivation_range": (70, 180),
            "lifespan_cost": 3,
            "npc_interact_chance": 0.4,
            "npc_scene": "组内交流",
            "is_bad": False,
        },
        {
            "name": "写学术专著",
            "description": "总结多年研究成果，撰写高水平的学术专著。",
            "cultivation_range": (90, 220),
            "lifespan_cost": 4,
            "npc_interact_chance": 0.1,
            "npc_scene": "出版社编辑",
            "is_bad": False,
        },
        {
            "name": "抢学生一作成果",
            "description": "强行将自己列为学生论文的第一作者，霸占学术成果。",
            "cultivation_range": (60, 180),
            "lifespan_cost": 4,
            "npc_interact_chance": 0.65,
            "npc_scene": "学生抗议",
            "is_bad": True,
            "penalty_range": (-100, -50),
        },
        {
            "name": "学术霸凌被举报",
            "description": "长期打压同事和学生，被联名举报到学术道德委员会。",
            "cultivation_range": (70, 200),
            "lifespan_cost": 5,
            "npc_interact_chance": 0.7,
            "npc_scene": "被举报调查",
            "is_bad": True,
            "penalty_range": (-120, -60),
        },
        {
            "name": "奇遇骰子",
            "description": "路边捡到一个神秘骰子，掷出后竟引发天地异象！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "奇遇骰子",
        },
        {
            "name": "灵石猜猜看",
            "description": "路边遇到一个神秘庄家，邀你玩猜数字游戏，赢取灵石！",
            "cultivation_range": (0, 0),
            "lifespan_cost": 0,
            "npc_interact_chance": 0,
            "npc_scene": "",
            "is_bad": False,
            "game": "灵石猜猜看",
        },
    ],
}


def get_preset_events(realm_level):
    """获取指定境界的预设事件列表"""
    return PRESET_EVENTS.get(realm_level, [])


def get_preset_event_by_name(realm_level, event_name):
    """根据事件名称获取指定境界的事件"""
    events = PRESET_EVENTS.get(realm_level, [])
    for event in events:
        if event["name"] == event_name:
            return event
    return None


